server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: UNIVERSITY-CONNECT
  datasource:
    url: ${DB_HOST_URL}:${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


jwt_configs:
  secret: ${APP_JWT_SECRET}
  access_token_validity_s: ${APP_JWT_ACCESS_VALIDITY_S}
  refresh_token_validity_s: ${APP_JWT_REFRESH_VALIDITY_S}

logging:
  level:
    root: info
    org:
      springframework:
        security: info

