server:
  port: ${SERVER_PORT}
spring:
  application:
    name: UNIVERSITY-CONNECT
  datasource:
    url: ${DB_HOST_URL}:${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update


jwt_configs:
  secret: ${APP_JWT_SECRET}
  access_token_validity_ms: ${APP_JWT_ACCESS_VALIDITY_MS}
  refresh_token_validity_ms: ${APP_JWT_REFRESH_VALIDITY_MS}

logging:
  level:
    root: info
    org:
      springframework:
        security: info

